<?php
require_once('system/core/Production.php');
require_once('system/config/settings.php');
require_once('system/core/Database.php');
require_once('system/core/Bootstrap.php');
require_once('system/core/Controller.php');
require_once('system/core/View.php');
require_once('system/core/Crypto.php');
require_once('system/core/Model.php');
require_once('system/core/Template.php');
require_once('system/core/Input.php');
require_once('system/core/Errors.php');
require_once('system/core/Library.php');
require_once('system/core/Session.php');
require_once('system/core/Security.php');
require_once('system/core/Detector.php');
require_once('system/core/Helper.php');
?>